"""add nsfw_score crop and referral unique constraint

Revision ID: 6f98cdbf0b57
Revises: b3c4d5e6f7a8
Create Date: 2026-08-05 11:20:19.208542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f98cdbf0b57'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('nsfw_score', sa.Float(), nullable=True))
    op.add_column('photos', sa.Column('crop', sa.JSON(), nullable=True))
    op.create_unique_constraint('uq_referral_rewards_invited', 'referral_rewards', ['invited_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_referral_rewards_invited', 'referral_rewards', type_='unique')
    op.drop_column('photos', 'crop')
    op.drop_column('photos', 'nsfw_score')
    # ### end Alembic commands ###
