"""add language to prompts

Revision ID: 79940e33a29d
Revises: 30e15dca97b1
Create Date: 2026-06-22 13:43:47.134350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79940e33a29d'
down_revision: Union[str, Sequence[str], None] = '30e15dca97b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('language', sa.String(length=5), nullable=False))
    op.create_unique_constraint('uq_prompts_question_language', 'prompts', ['question', 'language'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_prompts_question_language', 'prompts', type_='unique')
    op.drop_column('prompts', 'language')
    # ### end Alembic commands ###
