"""add_performance_indexes

Revision ID: 7f10ad4c02b9
Revises: f238700864fd
Create Date: 2026-06-28 11:35:55.157881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f10ad4c02b9'
down_revision: Union[str, Sequence[str], None] = 'f238700864fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_blocks_blocked', 'blocks', ['blocked_id'], unique=False)
    op.create_index('idx_blocks_blocker', 'blocks', ['blocker_id'], unique=False)
    op.create_index('idx_matches_user1_time', 'matches', ['user1_id', 'matched_at'], unique=False)
    op.create_index('idx_matches_user2_time', 'matches', ['user2_id', 'matched_at'], unique=False)
    op.create_index('idx_matches_users_pair', 'matches', ['user1_id', 'user2_id'], unique=False)
    op.create_index('idx_messages_match_recent', 'messages', ['match_id', 'sent_at'], unique=False, postgresql_where=sa.text('is_deleted_for_all = false'))
    op.create_index('idx_messages_match_sent', 'messages', ['match_id', 'sent_at'], unique=False)
    op.create_index('idx_messages_receiver_delivered', 'messages', ['receiver_id', 'is_delivered'], unique=False, postgresql_where=sa.text('is_delivered = false'))
    op.create_index('idx_messages_receiver_read', 'messages', ['receiver_id', 'is_read'], unique=False, postgresql_where=sa.text('is_read = false'))
    op.create_index('idx_notifications_user_unread', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_index('idx_photos_status', 'photos', ['status', 'created_at'], unique=False)
    op.create_index('idx_photos_user_id', 'photos', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_photos_user_main', 'photos', ['user_id', 'is_main'], unique=False, postgresql_where=sa.text('is_main = true'))
    op.create_index('idx_swipes_swipee_swiper_type', 'swipes', ['to_user', 'from_user', 'direction'], unique=False)
    op.create_index('idx_swipes_swiper_type', 'swipes', ['from_user', 'direction'], unique=False)
    op.create_index('idx_user_interests_interest', 'user_interests', ['interest_id'], unique=False)
    op.create_index('idx_user_interests_user', 'user_interests', ['user_id'], unique=False)
    op.create_index('idx_profiles_birth_date', 'user_profiles', ['birth_date'], unique=False)
    op.create_index('idx_profiles_body_type', 'user_profiles', ['body_type'], unique=False)
    op.create_index('idx_profiles_city', 'user_profiles', ['city'], unique=False)
    op.create_index('idx_profiles_country', 'user_profiles', ['country'], unique=False)
    op.create_index('idx_profiles_drinking', 'user_profiles', ['drinking'], unique=False)
    op.create_index('idx_profiles_education', 'user_profiles', ['education'], unique=False)
    op.create_index('idx_profiles_ethnicity', 'user_profiles', ['ethnicity'], unique=False)
    op.create_index('idx_profiles_gender', 'user_profiles', ['gender'], unique=False)
    op.create_index('idx_profiles_height', 'user_profiles', ['height'], unique=False)
    op.create_index('idx_profiles_is_verified', 'user_profiles', ['is_verified'], unique=False, postgresql_where=sa.text('is_verified = true'))
    op.create_index('idx_profiles_lat_lng', 'user_profiles', ['lat', 'lng'], unique=False)
    op.create_index('idx_profiles_premium_until', 'user_profiles', ['premium_until'], unique=False)
    op.create_index('idx_profiles_province', 'user_profiles', ['province'], unique=False)
    op.create_index('idx_profiles_relationship_status', 'user_profiles', ['relationship_status'], unique=False)
    op.create_index('idx_profiles_religion', 'user_profiles', ['religion'], unique=False)
    op.create_index('idx_profiles_smoking', 'user_profiles', ['smoking'], unique=False)
    op.create_index('idx_user_prompts_user', 'user_prompts', ['user_id'], unique=False)
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_users_last_seen', 'users', ['last_seen_at'], unique=False)
    op.create_index('idx_users_registration_status', 'users', ['registration_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_registration_status', table_name='users')
    op.drop_index('idx_users_last_seen', table_name='users')
    op.drop_index('idx_users_is_active', table_name='users', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_user_prompts_user', table_name='user_prompts')
    op.drop_index('idx_profiles_smoking', table_name='user_profiles')
    op.drop_index('idx_profiles_religion', table_name='user_profiles')
    op.drop_index('idx_profiles_relationship_status', table_name='user_profiles')
    op.drop_index('idx_profiles_province', table_name='user_profiles')
    op.drop_index('idx_profiles_premium_until', table_name='user_profiles')
    op.drop_index('idx_profiles_lat_lng', table_name='user_profiles')
    op.drop_index('idx_profiles_is_verified', table_name='user_profiles', postgresql_where=sa.text('is_verified = true'))
    op.drop_index('idx_profiles_height', table_name='user_profiles')
    op.drop_index('idx_profiles_gender', table_name='user_profiles')
    op.drop_index('idx_profiles_ethnicity', table_name='user_profiles')
    op.drop_index('idx_profiles_education', table_name='user_profiles')
    op.drop_index('idx_profiles_drinking', table_name='user_profiles')
    op.drop_index('idx_profiles_country', table_name='user_profiles')
    op.drop_index('idx_profiles_city', table_name='user_profiles')
    op.drop_index('idx_profiles_body_type', table_name='user_profiles')
    op.drop_index('idx_profiles_birth_date', table_name='user_profiles')
    op.drop_index('idx_user_interests_user', table_name='user_interests')
    op.drop_index('idx_user_interests_interest', table_name='user_interests')
    op.drop_index('idx_swipes_swiper_type', table_name='swipes')
    op.drop_index('idx_swipes_swipee_swiper_type', table_name='swipes')
    op.drop_index('idx_photos_user_main', table_name='photos', postgresql_where=sa.text('is_main = true'))
    op.drop_index('idx_photos_user_id', table_name='photos')
    op.drop_index('idx_photos_status', table_name='photos')
    op.drop_index('idx_notifications_user_unread', table_name='notifications')
    op.drop_index('idx_messages_receiver_read', table_name='messages', postgresql_where=sa.text('is_read = false'))
    op.drop_index('idx_messages_receiver_delivered', table_name='messages', postgresql_where=sa.text('is_delivered = false'))
    op.drop_index('idx_messages_match_sent', table_name='messages')
    op.drop_index('idx_messages_match_recent', table_name='messages', postgresql_where=sa.text('is_deleted_for_all = false'))
    op.drop_index('idx_matches_users_pair', table_name='matches')
    op.drop_index('idx_matches_user2_time', table_name='matches')
    op.drop_index('idx_matches_user1_time', table_name='matches')
    op.drop_index('idx_blocks_blocker', table_name='blocks')
    op.drop_index('idx_blocks_blocked', table_name='blocks')
    # ### end Alembic commands ###
