"""initial schema

Revision ID: ad655e0fe278
Revises: 
Create Date: 2026-08-08 09:26:01.070377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad655e0fe278'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_logs_admin', 'admin_logs', ['admin_id', 'created_at'], unique=False)
    op.create_index('idx_admin_logs_target', 'admin_logs', ['target_type', 'target_id'], unique=False)
    op.create_table('interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question', 'language', name='uq_prompts_question_language')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('registration_status', sa.String(length=20), nullable=False),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('referred_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_users_last_seen', 'users', ['last_seen_at'], unique=False)
    op.create_index('idx_users_registration_status', 'users', ['registration_status'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blocker_id', sa.UUID(), nullable=False),
    sa.Column('blocked_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_block_blocker_blocked')
    )
    op.create_index('idx_blocks_blocked', 'blocks', ['blocked_id'], unique=False)
    op.create_index('idx_blocks_blocker', 'blocks', ['blocker_id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('initiator_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_ended', sa.Boolean(), nullable=False),
    sa.Column('ended_by', sa.UUID(), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_for_initiator', sa.Boolean(), nullable=False),
    sa.Column('deleted_for_recipient', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ended_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chats_initiator_time', 'chats', ['initiator_id', 'updated_at'], unique=False)
    op.create_index('idx_chats_recipient_time', 'chats', ['recipient_id', 'updated_at'], unique=False)
    op.create_index('uq_chats_active_pair', 'chats', [sa.literal_column('LEAST(initiator_id, recipient_id)'), sa.literal_column('GREATEST(initiator_id, recipient_id)')], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('daily_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('likes_used', sa.SmallInteger(), nullable=True),
    sa.Column('chats_used', sa.SmallInteger(), nullable=True),
    sa.Column('ad_likes_bonus', sa.SmallInteger(), nullable=True),
    sa.Column('ad_chats_bonus', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_limits_user_date')
    )
    op.create_table('device_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'token', name='uq_device_token_user_token')
    )
    op.create_index('idx_device_tokens_user', 'device_tokens', ['user_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user1_id', sa.UUID(), nullable=False),
    sa.Column('user2_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user1_id', 'user2_id')
    )
    op.create_index('idx_matches_user1_time', 'matches', ['user1_id', 'matched_at'], unique=False)
    op.create_index('idx_matches_user2_time', 'matches', ['user2_id', 'matched_at'], unique=False)
    op.create_index('idx_matches_users_pair', 'matches', ['user1_id', 'user2_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_user_unread', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('order', sa.SmallInteger(), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('nsfw_score', sa.Float(), nullable=True),
    sa.Column('face_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('crop', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_photos_status', 'photos', ['status', 'created_at'], unique=False)
    op.create_index('idx_photos_user_id', 'photos', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_photos_user_main', 'photos', ['user_id', 'is_main'], unique=False, postgresql_where=sa.text('is_main = true'))
    op.create_table('referral_rewards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inviter_id', sa.UUID(), nullable=False),
    sa.Column('invited_id', sa.UUID(), nullable=False),
    sa.Column('inviter_days', sa.SmallInteger(), nullable=True),
    sa.Column('invited_days', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invited_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invited_id', name='uq_referral_rewards_invited')
    )
    op.create_table('review_rewards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('days_granted', sa.SmallInteger(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform', name='uq_review_rewards_user_platform')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_user', sa.UUID(), nullable=False),
    sa.Column('to_user', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['from_user'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_user', 'to_user')
    )
    op.create_index('idx_swipes_swipee_swiper_type', 'swipes', ['to_user', 'from_user', 'direction'], unique=False)
    op.create_index('idx_swipes_swiper_type', 'swipes', ['from_user', 'direction'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('interest_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'interest_id', name='uq_user_interests_user_interest')
    )
    op.create_index('idx_user_interests_interest', 'user_interests', ['interest_id'], unique=False)
    op.create_index('idx_user_interests_user', 'user_interests', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('sexual_orientation', sa.String(length=20), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('height', sa.SmallInteger(), nullable=True),
    sa.Column('weight', sa.SmallInteger(), nullable=True),
    sa.Column('body_type', sa.String(length=20), nullable=True),
    sa.Column('relationship_status', sa.String(length=20), nullable=True),
    sa.Column('living_situation', sa.String(length=30), nullable=True),
    sa.Column('children_status', sa.String(length=20), nullable=True),
    sa.Column('smoking', sa.String(length=20), nullable=True),
    sa.Column('drinking', sa.String(length=20), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('education', sa.String(length=50), nullable=True),
    sa.Column('workplace', sa.String(length=100), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('ethnicity', sa.String(length=50), nullable=True),
    sa.Column('political_orientation', sa.String(length=30), nullable=True),
    sa.Column('lat', sa.Double(), nullable=True),
    sa.Column('lng', sa.Double(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('location_manual', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('premium_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_profiles_birth_date', 'user_profiles', ['birth_date'], unique=False)
    op.create_index('idx_profiles_body_type', 'user_profiles', ['body_type'], unique=False)
    op.create_index('idx_profiles_city', 'user_profiles', ['city'], unique=False)
    op.create_index('idx_profiles_country', 'user_profiles', ['country'], unique=False)
    op.create_index('idx_profiles_drinking', 'user_profiles', ['drinking'], unique=False)
    op.create_index('idx_profiles_education', 'user_profiles', ['education'], unique=False)
    op.create_index('idx_profiles_ethnicity', 'user_profiles', ['ethnicity'], unique=False)
    op.create_index('idx_profiles_gender', 'user_profiles', ['gender'], unique=False)
    op.create_index('idx_profiles_height', 'user_profiles', ['height'], unique=False)
    op.create_index('idx_profiles_is_verified', 'user_profiles', ['is_verified'], unique=False, postgresql_where=sa.text('is_verified = true'))
    op.create_index('idx_profiles_lat_lng', 'user_profiles', ['lat', 'lng'], unique=False)
    op.create_index('idx_profiles_premium_until', 'user_profiles', ['premium_until'], unique=False)
    op.create_index('idx_profiles_province', 'user_profiles', ['province'], unique=False)
    op.create_index('idx_profiles_relationship_status', 'user_profiles', ['relationship_status'], unique=False)
    op.create_index('idx_profiles_religion', 'user_profiles', ['religion'], unique=False)
    op.create_index('idx_profiles_smoking', 'user_profiles', ['smoking'], unique=False)
    op.create_table('user_prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'prompt_id', name='uq_user_prompts_user_prompt')
    )
    op.create_index('idx_user_prompts_user', 'user_prompts', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hide_last_seen', sa.Boolean(), nullable=True),
    sa.Column('hide_online_status', sa.Boolean(), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=True),
    sa.Column('like_notifications', sa.Boolean(), nullable=True),
    sa.Column('match_notifications', sa.Boolean(), nullable=True),
    sa.Column('message_notifications', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('dark_mode', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('reply_to_id', sa.UUID(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('media_duration', sa.Integer(), nullable=True),
    sa.Column('media_size', sa.Integer(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('is_delivered', sa.Boolean(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_deleted_for_sender', sa.Boolean(), nullable=True),
    sa.Column('is_deleted_for_receiver', sa.Boolean(), nullable=True),
    sa.Column('is_deleted_for_all', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name='fk_messages_chat_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_chat_recent', 'messages', ['chat_id', 'sent_at'], unique=False, postgresql_where=sa.text('is_deleted_for_all = false'))
    op.create_index('idx_messages_chat_sent', 'messages', ['chat_id', 'sent_at'], unique=False)
    op.create_index('idx_messages_receiver_delivered', 'messages', ['receiver_id', 'is_delivered'], unique=False, postgresql_where=sa.text('is_delivered = false'))
    op.create_index('idx_messages_receiver_read', 'messages', ['receiver_id', 'is_read'], unique=False, postgresql_where=sa.text('is_read = false'))
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reported_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('is_message_report', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_index('idx_messages_receiver_read', table_name='messages', postgresql_where=sa.text('is_read = false'))
    op.drop_index('idx_messages_receiver_delivered', table_name='messages', postgresql_where=sa.text('is_delivered = false'))
    op.drop_index('idx_messages_chat_sent', table_name='messages')
    op.drop_index('idx_messages_chat_recent', table_name='messages', postgresql_where=sa.text('is_deleted_for_all = false'))
    op.drop_table('messages')
    op.drop_table('user_settings')
    op.drop_index('idx_user_prompts_user', table_name='user_prompts')
    op.drop_table('user_prompts')
    op.drop_index('idx_profiles_smoking', table_name='user_profiles')
    op.drop_index('idx_profiles_religion', table_name='user_profiles')
    op.drop_index('idx_profiles_relationship_status', table_name='user_profiles')
    op.drop_index('idx_profiles_province', table_name='user_profiles')
    op.drop_index('idx_profiles_premium_until', table_name='user_profiles')
    op.drop_index('idx_profiles_lat_lng', table_name='user_profiles')
    op.drop_index('idx_profiles_is_verified', table_name='user_profiles', postgresql_where=sa.text('is_verified = true'))
    op.drop_index('idx_profiles_height', table_name='user_profiles')
    op.drop_index('idx_profiles_gender', table_name='user_profiles')
    op.drop_index('idx_profiles_ethnicity', table_name='user_profiles')
    op.drop_index('idx_profiles_education', table_name='user_profiles')
    op.drop_index('idx_profiles_drinking', table_name='user_profiles')
    op.drop_index('idx_profiles_country', table_name='user_profiles')
    op.drop_index('idx_profiles_city', table_name='user_profiles')
    op.drop_index('idx_profiles_body_type', table_name='user_profiles')
    op.drop_index('idx_profiles_birth_date', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index('idx_user_interests_user', table_name='user_interests')
    op.drop_index('idx_user_interests_interest', table_name='user_interests')
    op.drop_table('user_interests')
    op.drop_table('tickets')
    op.drop_index('idx_swipes_swiper_type', table_name='swipes')
    op.drop_index('idx_swipes_swipee_swiper_type', table_name='swipes')
    op.drop_table('swipes')
    op.drop_table('subscriptions')
    op.drop_table('review_rewards')
    op.drop_table('referral_rewards')
    op.drop_index('idx_photos_user_main', table_name='photos', postgresql_where=sa.text('is_main = true'))
    op.drop_index('idx_photos_user_id', table_name='photos')
    op.drop_index('idx_photos_status', table_name='photos')
    op.drop_table('photos')
    op.drop_index('idx_notifications_user_unread', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_matches_users_pair', table_name='matches')
    op.drop_index('idx_matches_user2_time', table_name='matches')
    op.drop_index('idx_matches_user1_time', table_name='matches')
    op.drop_table('matches')
    op.drop_index('idx_device_tokens_user', table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_table('daily_limits')
    op.drop_index('uq_chats_active_pair', table_name='chats', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_chats_recipient_time', table_name='chats')
    op.drop_index('idx_chats_initiator_time', table_name='chats')
    op.drop_table('chats')
    op.drop_index('idx_blocks_blocker', table_name='blocks')
    op.drop_index('idx_blocks_blocked', table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_registration_status', table_name='users')
    op.drop_index('idx_users_last_seen', table_name='users')
    op.drop_index('idx_users_is_active', table_name='users', postgresql_where=sa.text('is_active = true'))
    op.drop_table('users')
    op.drop_table('prompts')
    op.drop_table('interests')
    op.drop_index('idx_admin_logs_target', table_name='admin_logs')
    op.drop_index('idx_admin_logs_admin', table_name='admin_logs')
    op.drop_table('admin_logs')
    # ### end Alembic commands ###
