"""add admin_logs

Revision ID: c8e7e106135e
Revises: a1b2c3d4e5f6
Create Date: 2026-07-15 16:18:46.720931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e7e106135e'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_logs_admin', 'admin_logs', ['admin_id', 'created_at'], unique=False)
    op.create_index('idx_admin_logs_target', 'admin_logs', ['target_type', 'target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_admin_logs_target', table_name='admin_logs')
    op.drop_index('idx_admin_logs_admin', table_name='admin_logs')
    op.drop_table('admin_logs')
    # ### end Alembic commands ###
